-- Financial Planning module (SETUP.md "Financial Planning module") — recurring revenue tracking
-- (fp_customers → fp_expected_dues → fp_collections) and expense tracking (fp_expense_templates,
-- auto-booked monthly, vs. one-off fp_expenses rows) for the Accounting module
-- (frontend/accounting.html). D1-backed like the rest of Accounting — a genuinely new data shape
-- (billing cycles, aging, monthly generation) with no existing NocoDB reader, same reasoning as
-- every other D1 module in this file.
--
-- Distinct on purpose from the existing "👤 Customers" tab in accounting.html, which is a live
-- ERPNext passthrough with no local storage at all (no mirror table, no persisted mapping) —
-- fp_customers is this app's own recurring-billing customer record, independent of whether
-- ERPNext is even connected. A lead can optionally link to one via lead_id, same "plain integer
-- reference, not a SQL foreign key" convention as accounting_documents.linked_doc_id (a customer
-- record must still resolve even if the originating lead is later deleted/merged).

CREATE TABLE IF NOT EXISTS fp_customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  lead_id INTEGER,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  plan_name TEXT,
  monthly_value REAL NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'INR',
  billing_cycle TEXT NOT NULL DEFAULT 'monthly',   -- monthly|quarterly|yearly
  billing_day INTEGER NOT NULL DEFAULT 1,          -- day of month an Expected Fund is due; clamped 1-28 so due_date is always a valid calendar date
  start_date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',           -- active|paused|cancelled
  notes TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fp_customers_client ON fp_customers(client_id);
CREATE INDEX IF NOT EXISTS idx_fp_customers_lead ON fp_customers(client_id, lead_id);

-- One row per (customer, billing period) — auto-generated by the monthly cron
-- (runFinancialPlanningMonthlyForAllClients), never duplicated thanks to the unique index below
-- (a re-run on the same day, or a redelivered cron tick, just hits the constraint and no-ops).
-- period_key is always 'YYYY-MM', including for quarterly/yearly customers — it's only actually
-- generated on the applicable months (see fpGenerateForClient), so the key itself doesn't need a
-- different shape per cycle. collected_amount is denormalized (kept in sync in the same
-- transaction whenever a linked fp_collections row is created/deleted) rather than summed via a
-- join on every read, same "precomputed total, not derived from a join" convention as
-- accounting_documents.total.
CREATE TABLE IF NOT EXISTS fp_expected_dues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  period_key TEXT NOT NULL,
  amount REAL NOT NULL,
  currency TEXT NOT NULL,
  due_date TEXT NOT NULL,
  collected_amount REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'open',    -- open|partial|paid|void
  reminder_sent_at TEXT,
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fp_expected_dues_unique ON fp_expected_dues(customer_id, period_key);
CREATE INDEX IF NOT EXISTS idx_fp_expected_dues_client ON fp_expected_dues(client_id, due_date);

-- Actual payment received — either against a specific Expected Fund (expected_due_id set) or an
-- ad-hoc/advance collection with no linked due (expected_due_id NULL). razorpay_payment_id is
-- only ever set by the Razorpay webhook (handleRazorpayWebhook) — its own unique index means a
-- redelivered webhook for the same payment is recognized and ignored rather than double-counted,
-- the same "unique index as the dedupe mechanism" idiom as calendar_event_sends.
CREATE TABLE IF NOT EXISTS fp_collections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  expected_due_id INTEGER,
  amount REAL NOT NULL,
  currency TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'bank',   -- bank|upi|razorpay|cash|other
  razorpay_payment_id TEXT,
  collected_at TEXT NOT NULL,
  notes TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fp_collections_client ON fp_collections(client_id, collected_at);
CREATE INDEX IF NOT EXISTS idx_fp_collections_due ON fp_collections(expected_due_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fp_collections_razorpay_unique ON fp_collections(razorpay_payment_id) WHERE razorpay_payment_id IS NOT NULL;

-- Fixed Recurring expense definitions (rent, salaries, SaaS tools) — auto-booked into fp_expenses
-- on the 1st of each month by the same monthly cron that generates Expected Funds. One-time
-- expenses skip this table entirely and are inserted straight into fp_expenses with template_id
-- NULL.
CREATE TABLE IF NOT EXISTS fp_expense_templates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general',
  amount REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fp_expense_templates_client ON fp_expense_templates(client_id);

CREATE TABLE IF NOT EXISTS fp_expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  template_id INTEGER,
  type TEXT NOT NULL DEFAULT 'onetime',   -- fixed|onetime
  category TEXT NOT NULL DEFAULT 'general',
  name TEXT NOT NULL,
  amount REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  period_key TEXT,     -- set only on auto-booked 'fixed' rows; the dedup key alongside template_id
  expense_date TEXT NOT NULL,
  notes TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fp_expenses_client ON fp_expenses(client_id, expense_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fp_expenses_template_period_unique ON fp_expenses(template_id, period_key) WHERE template_id IS NOT NULL;

-- Opt-in gate for the monthly generation cron and the overdue-reminder sweep — same "only scan
-- clients that ever turned this on" pattern as review_config, cheaper than a full CLIENTS table
-- scan every tick. A client's first fp_customers/fp_expense_templates write should upsert a row
-- here with enabled=1 so the cron picks them up automatically.
CREATE TABLE IF NOT EXISTS fp_config (
  client_id INTEGER PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 1,
  reminders_enabled INTEGER NOT NULL DEFAULT 1,
  razorpay_key_id TEXT,
  razorpay_key_secret TEXT,
  razorpay_webhook_secret TEXT,
  updated_at TEXT NOT NULL
);
