-- AI Business Snapshot cache (Financial Planning — see worker.js's "AI-Supported Bookkeeping"
-- section) — a one-paragraph, plain-English monthly narrative generated by Gemini from this
-- client's own real fp_* numbers. Cached per calendar month (ai_snapshot_period, 'YYYY-MM') rather
-- than regenerated on every dashboard load, same "compute once, cache, explicit regenerate button"
-- shape as everywhere else in this app that wraps a paid/rate-limited API call behind a UI action.
ALTER TABLE fp_config ADD COLUMN ai_snapshot_text TEXT;
ALTER TABLE fp_config ADD COLUMN ai_snapshot_period TEXT;
ALTER TABLE fp_config ADD COLUMN ai_snapshot_generated_at TEXT;
