-- Projects module (SETUP.md "Projects module") — merging the legacy CLIENTS.manual_tasks blob
-- system into pm_tasks/pm_projects. These columns exist so every feature the old system had
-- (Lead linking, task categories, the Advanced Pipeline follow-up cadence's channel/mode/step,
-- client-facing completion notices, AI auto-stage suggestion, Google Calendar sync) has somewhere
-- to live on the new, real schema instead of being dropped in the move.

-- lead_id/lead_name: soft reference to a NocoDB Leads row (cross-database — Leads live in
-- NocoDB, pm_tasks lives in D1 — so this is a plain integer + a denormalized display name, not a
-- real FK, resolved through the Worker's /nocodb proxy same as everywhere else in this app).
-- category: the 6 fixed values from the old TASK_CATEGORIES (Sales/Follow-up/Admin/Support/
-- Marketing/Internal).
-- channel/mode/followup_step: written only by the Advanced Pipeline follow-up cadence
-- (pipelineAppendTask in worker.js) — which channel (whatsapp/call/email) and mode
-- (text/voice/video/call) the next touch should use, and which rung of the escalation ladder.
-- notify_customer: on completion, send an AI-rewritten status update to the linked lead/project's
-- client email.
-- ai_created: this task was auto-generated by the AI-suggest-next-task feature, not typed by a
-- human — display-only provenance flag.
-- auto_generated: written by system processes (the pipeline cadence, AI-suggest) rather than a
-- person clicking "+ Task" — used to let the cadence safely replace its own previous auto-task
-- for a lead without touching anything a human created by hand.
-- gcal_event_id: the linked Google Calendar event id once synced (see handleGcalSyncTask, reused
-- as-is from the legacy system — it already takes a generic {id,title,notes,due_date,due_time,
-- status,gcal_event_id} shape, so pm_tasks needed no backend changes there, just this column).
-- 'blocked' is a fifth valid value for the existing `status` column (todo/in_progress/review/done/
-- blocked) — no schema change needed for that, just application-level handling.
ALTER TABLE pm_tasks ADD COLUMN lead_id INTEGER;
ALTER TABLE pm_tasks ADD COLUMN lead_name TEXT;
ALTER TABLE pm_tasks ADD COLUMN category TEXT;
ALTER TABLE pm_tasks ADD COLUMN channel TEXT;
ALTER TABLE pm_tasks ADD COLUMN mode TEXT;
ALTER TABLE pm_tasks ADD COLUMN followup_step INTEGER;
ALTER TABLE pm_tasks ADD COLUMN notify_customer INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pm_tasks ADD COLUMN ai_created INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pm_tasks ADD COLUMN auto_generated INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pm_tasks ADD COLUMN gcal_event_id TEXT;
CREATE INDEX IF NOT EXISTS idx_pm_tasks_lead ON pm_tasks(client_id, lead_id);

-- client_email: who notify_customer emails go to for this project's tasks, when the task itself
-- has no linked lead (or the linked lead has no email) to resolve one from — a manual fallback,
-- same as the old system's freeform state.projects[].client_email.
-- ai_auto_stage_enabled: turns on AI-suggest-next-task when a task in this project completes
-- (same opt-in the old per-project ai_auto_stage_enabled flag was).
ALTER TABLE pm_projects ADD COLUMN client_email TEXT;
ALTER TABLE pm_projects ADD COLUMN ai_auto_stage_enabled INTEGER NOT NULL DEFAULT 0;

-- One row per client once handlePmMigrateLegacyTasks has converted their manual_tasks blob into
-- real pm_projects/pm_tasks/pm_task_dependencies rows — makes the migration route idempotent
-- (safe to re-run across the whole platform without doubling anyone up) and gives a plain audit
-- trail of what actually moved, since the source blob is left untouched rather than deleted.
CREATE TABLE IF NOT EXISTS pm_task_migrations (
  client_id INTEGER PRIMARY KEY,
  migrated_at TEXT NOT NULL,
  projects_count INTEGER NOT NULL DEFAULT 0,
  tasks_count INTEGER NOT NULL DEFAULT 0,
  deps_count INTEGER NOT NULL DEFAULT 0
);
